compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

# Disable postinstall scripts. Any packages which need it can be enabled individually with dependenciesMeta in package.json
enableScripts: false

# Enforce a minimal age for npm packages before they can be added/updated
npmMinimalAgeGate: 7

# Packages to ignore the minimal age gate. These are packages we vet ourselves.
npmPreapprovedPackages:
  - "@sofie-automation/*"
  - "@mos-connection/*"
  - "timeline-state-resolver"
  - "timeline-state-resolver-types"
  - "timeline-state-resolver-api"